# Generated by Django 4.1.7 on 2023-05-17 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='Signal_Files/')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(max_length=400, verbose_name='Descripcion del Proyecto')),
                ('sampleRate', models.FloatField(verbose_name='Frecuencia de muestreo (Hz)')),
                ('ganancia', models.IntegerField(verbose_name='Ganancia')),
                ('time', models.FloatField(verbose_name='Tiempo (seg)')),
                ('complete', models.BooleanField(verbose_name='Proyecto Finalizado')),
                ('rarFile', models.FileField(blank=True, upload_to='RAR_Files/', verbose_name='Archivo RAR')),
                ('article', models.FileField(blank=True, upload_to='Articles/', verbose_name='Articulo PDF')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='SignalType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Tipo de señal')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('I', 'Prefiere no especificar')], max_length=1, verbose_name='Genero')),
                ('observaciones', models.TextField(blank=True, max_length=100, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la prueba')),
                ('descripcion', models.TextField(max_length=400, verbose_name='Descripcion')),
                ('complete', models.BooleanField()),
                ('rarFile', models.FileField(blank=True, upload_to='RAR_Files/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB.proyecto', verbose_name='Proyecto')),
                ('voluntarios', models.ManyToManyField(through='WEB.Muestra', to='WEB.voluntario')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='signalType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB.signaltype', verbose_name='Tipo de señal'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('foto', models.FileField(upload_to='Img_Perfil/')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='muestra',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB.prueba'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='voluntario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB.voluntario'),
        ),
    ]
