# Generated by Django 4.1.7 on 2023-05-23 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WEB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ocupado', models.BooleanField()),
                ('proyecto', models.IntegerField(blank=True)),
                ('prueba', models.IntegerField(blank=True)),
                ('voluntario', models.IntegerField(blank=True)),
                ('fecha', models.DateField(blank=True)),
                ('archivo', models.FileField(upload_to='Buffer_Files/')),
                ('ch0', models.FloatField(blank=True)),
                ('ch1', models.FloatField(blank=True)),
                ('ch2', models.FloatField(blank=True)),
                ('ch3', models.FloatField(blank=True)),
                ('ch4', models.FloatField(blank=True)),
                ('ch5', models.FloatField(blank=True)),
                ('ch6', models.FloatField(blank=True)),
                ('ch7', models.FloatField(blank=True)),
                ('ch8', models.FloatField(blank=True)),
                ('ch9', models.FloatField(blank=True)),
                ('ch10', models.FloatField(blank=True)),
                ('ch11', models.FloatField(blank=True)),
                ('ch12', models.FloatField(blank=True)),
                ('ch13', models.FloatField(blank=True)),
                ('ch14', models.FloatField(blank=True)),
                ('ch15', models.FloatField(blank=True)),
                ('ch16', models.FloatField(blank=True)),
                ('ch17', models.FloatField(blank=True)),
                ('ch18', models.FloatField(blank=True)),
                ('ch19', models.FloatField(blank=True)),
                ('ch20', models.FloatField(blank=True)),
                ('ch21', models.FloatField(blank=True)),
                ('ch22', models.FloatField(blank=True)),
                ('ch23', models.FloatField(blank=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
